onstagram/blog/urls.py
from django.urls import path
from . import views
from .views import  dashboard,newpost,mypost,delete,search,likes,editpost, comment
urlpatterns = [
    path('indexdashboard/',dashboard, name='indexdashboard'),
    path('about/', views.about, name='about'),
    path('home/', views.home, name='home'),
    path('post/',newpost, name='postnew'),
    path('mypost/',mypost, name='mypost'),
    path('delete/<str:id>/', delete, name="delete"),
    path('search/',search, name='search'),
    path('editpost/<str:id>/',editpost, name='editpost'),
    path('home/likes/', likes, name='likes'),
    path('home/comment/', comment , name='comment'),
]

onstagram/onstagram/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("user.urls")),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onstagram/blog/models.py
import datetime
from distutils.command.upload import upload

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

""" Post model """
class Post(models.Model):
    title = models.CharField(max_length=150)
    content = models.CharField(max_length=400,null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="blogpost", blank=True)
    post_image = models.ImageField(upload_to="image", null=True)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk":self.pk})


""" Comment model """
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments" , on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=200)
    date_added = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return '%s - %s - %s' %(self.post.title, self.name, self.id)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk":self.pk})

onstagram/blog/forms.py
from django import forms
from django.forms import fields, widgets
from .models import Post, Comment

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control custom-txt','cols':'40','rows':'3'}), label='')
    class Meta:
        model = Comment
        fields = ['body',]

class PostForm(forms.ModelForm):
    content = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={"placeholder":"Dweet something...", "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )

    class Meta:
        model = Post
        exclude = ("author",)
class UpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","content","post_image",)

onstagram/blog/views.py
from pyexpat.errors import messages
from unittest import result
from django.shortcuts import render,redirect,get_object_or_404

from .models import Comment, Post
from user.models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import PostForm, UpdateForm
from django.shortcuts import (get_object_or_404, HttpResponseRedirect)

from django.http import JsonResponse
""" Home page with all posts """

@login_required
def home(request):
    profile = Profile.objects.get(pk=request.user.profile.pk)
    
    profile.following.add(profile)
    print(profile.following.add(profile))
    followed_posts = Post.objects.filter(
        author__profile__in=request.user.profile.following.all()
    ).order_by("-date_posted")

    profile = Profile.objects.get(pk=request.user.profile.pk)

    post1 = Post.objects.filter(likes = request.user)

    mypost = Post.objects.filter(
        author=request.user
    )

    comment_post = Comment.objects.all().order_by("date_added")
    


    
    return render(request,"blog/home.html",{"blogs": followed_posts,"profile":profile,"post":post1,"mypost":mypost, "comment_post" : comment_post})

@login_required
def dashboard(request):
    
    return render(
        request ,
        "blog/first.html",)
@login_required
def about(request):

    profile = Profile.objects.get(pk=request.user.profile.pk) 
    f=profile.following.all() 
    profiles= Profile.objects.all().exclude(follow_by__in=f)
    return render(
        request ,
        "blog/about.html",{"profile":profiles})
@login_required
def newpost(request):
    form = PostForm(request.POST, request.FILES or None)
    if request.method == "POST":
        print(request.FILES)
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.author = request.user
            dweet.save()
            return redirect("/home")
    return render(request,"blog/newpost.html",{"form": form})
"""  my post """
@login_required
def mypost(request): 
    post = Post.objects.filter(
        author=request.user
    )
    print(post)

    return render(
        request,
        "blog/mypost.html",{"blogs":post})

""" Edit my post """
@login_required
def editpost(request,id):
        post1 = Post.objects.get(pk=id)
        form = UpdateForm(request.POST or None, request.FILES, instance=post1)
        if form.is_valid():
             form.save()
             return redirect("/home")
        return render(request,"blog/editpost.html",{"post1": post1,"form": form})
""" Delete my post """
@login_required
def delete(request, id):
    blog = get_object_or_404(Post, pk=id) 
    blog.delete()
    user = request.user.profile.pk
    return redirect('/profile/'+str(user))

""" Search by post title or username """
@login_required
def search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
       
        posts = Post.objects.filter(title__contains=searched)
        return render(request, 'blog/search_results.html',{'searched':searched,'posts':posts})
    else:
        return render(request, 'blog/search_results.html',{})

""" like post """
@login_required
def likes(request):
    if request.method == "GET":
        post_like = request.GET.get('button_like')
        # action_like = request.GET.get('action_like')
        post = Post.objects.get(pk = post_like)
        check_like = ''

        try:
            check_like = post.likes.get( pk=request.user.profile.pk)
            
        except:
            check_like = ''

        if check_like != '' :
            print("xoa like", check_like)
            post.likes.remove(request.user)
        else:
            print("like")
            post.likes.add(request.user)
        
        count_like = post.likes.count()
        print(count_like)

    return JsonResponse({"valid":"tao ne", "post_like" : count_like }, status = 200)

@login_required
def comment(request):
    if request.method == "GET":
        comment_body = request.GET.get('comment_body')
        post_id = request.GET.get('post_id')
        post = Post.objects.get(pk = post_id)
        print(post_id)
        print(comment_body)

        cmt = Comment.objects.create(post = post, name = request.user, body = comment_body )

        comment_post = Comment.objects.get(pk = cmt.pk)
        comment_time = comment_post.date_added
        comment_user = comment_post.name.username
        # user_image = cmt.name.profile.image
    return JsonResponse({ "comment_post": comment_post.body , "comment_time": comment_time, "comment_user": comment_user  }, status = 200)

onstagram/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block title %}Suggestion for you{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
<div class="col-md-8 m-auto">
    <div class="content-section">
        <h1 class="subtitle is-2">Suggestion for you</h1>
        <ul class="menu-list">
            {% for p in profile %}
            <a href="/profile/{{p.pk}}" style="color: #524b4b; text-decoration: none;">
                <li class="box" style="list-style-type: none;">
                    <img class="rounded-circle account-img" src="/user/media/{{ p.image }}" alt="" id="preview-img">
                    <span style="    font-size: 25px;font-weight: 600;"> {{p.user.username}}</span>
                </li>
            </a>
            {% endfor %}
        </ul>


        <br>

    </div>
</div>


{% endblock %}

onstagram/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css" integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'main.css' %}">
    
    <title>{% block title %}{% endblock %}</title>

</head>

<body>
    <header class="site-header" id="header" style="position: sticky; top: 0;z-index: 100">

    <!-- NAVBAR -->
    {% include 'blog/navbar.html' %}
  </header>

  <!-- MAIN SECTION -->
  <main role="main" class="container">
    <div class="row">




      {% block content %}{% endblock %}


    </div>
  </main>

  {% block script %}{% endblock %}
  <!-- SCRIPTS -->

  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"
    integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw=="
    crossorigin="anonymous"></script>

  <!-- ajax -->
  <script>
    $(document).on('submit', '.commentForm', function (event) {
      event.preventDefault();
      

      var form = new FormData(this);
      var comment_body = form.get('comment');
      var post_id = form.get('id_post');
      
      $('#comment_body_'+post_id).val("")
      $.ajax({

        url: 'comment/',
        type: 'get',
        data: {
          comment_body: comment_body,
          post_id: post_id 

       },
        success: function (response) {
          $('#comment_'+post_id).prepend(' <div> <img src="{{user.profile.image.url}}" '+ 
                                          'style="height: 30px; width:30px" class="border border-success rounded-circle"/>'+ 
                                          ' <span class="tag is-light is-medium">'
                                          +response["comment_post"]+ '</span>'+
                                          
                                          '<span class="is-small has-text-grey-light">'+
                                          ' ( '+response["comment_time"]+' by '+response["comment_user"]+') </span> '+
                                        
                                        
                                          '</div>  </br>');
          console.log(response["comment_post"]);
          
        }
      })
      
      
    });
  </script>

</body>

</html>

onstagram/blog/templates/blog/delete_view.html
<div class="main">
	<!-- Create a Form -->
	<form method="POST" >
		<!-- Security token by Django -->
		{% csrf_token %}
		Are you want to delete this item ?
		<input type="submit" value="Yes" />
		<a href="/home">Cancel </a>
	</form>
</div>

onstagram/blog/templates/blog/editpost.html
{% extends "blog/base.html" %}

{% block title %}About{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
<style>
    label,h1,h2 {
    font-weight: bold;
    margin-bottom: 10px;
    margin-top: 10px;
}
</style>
<div class="col-md-8 m-auto">
    <div class="content-section">
        <h1 class="subtitle is-2" style="color: blueviolet;">Edit Post</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2> Title: <h2>
            <input class="input is-primary" type="text" name="title"  placeholder="Title something..." maxlength="150" required id="id_title" 
            value="{{ post1.title }}"><br>
            <h2> Content: <h2>
                <textarea  name="content" cols="30" rows="10" placeholder="Dweet something..."  class="textarea is-link" required id="id_content">{{ post1.content }}</textarea>

            <h2>Pictures: </h2>
            <img class="rounded-circle account-img" src="/user/media/{{ post1.post_image }}" id="preview-img">
            <input type="file" name="post_image" accept="image/*" id="id_post_image" >
            <button class="button is-success is-fullwidth is-medium mt-5"
                    type="submit">Save Post
            </button> 

        </form>
        
        <br>

    </div>
</div>
<script>
    const reader = new FileReader();
    const fileInput = document.getElementById("id_post_image");
    const img = document.getElementById("preview-img");
    reader.onload = e => {
        img.src = e.target.result;
    }
    fileInput.addEventListener('change', e => {
        const f = e.target.files[0];
        reader.readAsDataURL(f);
    })
</script>
<script>
    var date = new Date();
    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();
    var hours =date.getHours();
    var miu =date.getMinutes();
    var secon =date.getSeconds();
    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
    var today = year + "-" + month + "-" + day + " " +hours+":"+miu+":"+secon;    
    document.getElementById("id_date_posted").value = today;
    </script>
{% endblock %}

onstagram/blog/templates/blog/first.html
{% extends "blog/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<!-- ADDITIONAL STYLING -->

<style>
  body{
    background-color: #fff;
  }
</style>

<div>
    
    <!-- Page Hero-->
    <section class=" page-header page-header-light bg-white mt-4 container">
      <div class="page-header-content pt-5">
          <div class="container">
              <div class="row align-items-center">
                  <div class="col-lg-6 " data-aos="fade-up">
                      <h1 style="" class="page-header-title font-weight-bold">Let’s Wow your online presence</h1>
                      <br>
                      <p class="page-header-text mb-5">
                        Surround yourself with people who are going to lift you higher. Join today and share your thoughts.
                        <br><br>
                        Designed and developed by <a target="_blank" href="https://github.com/Ronik22">Ronik Bhattacharjee</a>
                      </p>

                      {% if user.is_authenticated %}
                        <a class="btn btn-lg btn-primary font-weight-bold mr-2 rounded-pill px-4 py-2" href="#">Get Started</a>
                        <a class="btn btn-lg btn-primary-soft text-primary font-weight-bold" href="#"><i class="far fa-check-circle"></i>&nbsp;LOGGED IN</a>
                      {% else %}
                        <a class="btn btn-lg btn-primary font-weight-bold mr-2 rounded-pill px-4 py-2" href="{% url 'register' %}">REGISTER</a>
                        <a class="btn btn-lg btn-primary-soft text-primary font-weight-bold" href="#">LOGIN</a>
                      {% endif %}
                  </div>
                  <div class="col-lg-6 d-none d-lg-block" data-aos="fade-up" data-aos-delay="100"><img class="img-fluid" src="/static/blog/images/undraw_social_interaction_cy9i.png" /></div>
              </div>
          </div>
      </div>
      <br>
    </section>

</div>

{% endblock %}

onstagram/blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'home1.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
<div class="post">
  {% for blog in blogs %}
  <div class="card">
    <div class="top">
      <div class="userDetails">
        <div class="profile_img">
          <img class="cover" src="/user/media/{{blog.author.profile.image}}" alt="">
        </div>
        <div>
          <h3>{{blog.author.username}}</h3>
          <span class="postTime">{{ blog.date_posted }}</span>
        </div>
      </div>
      <div id="action_{{blog.pk}}" style="display: none;">
        <a href="{% url 'editpost' blog.id %}"><i style="color: black;" class="fa fa-cog" aria-hidden="true"></i></a>
        <a style="margin-left: 10px;" href="{% url 'delete' blog.id %}" Onclick="return ConfirmDelete();"><i
            style="color: black;" class="fa fa-trash" aria-hidden="true"></i>

        </a>
      </div>
    </div>
    <div class="imgBx">
      <img class="cover" src="/user/media/{{blog.post_image}}" alt="">
    </div>
    <h4 class="title">{{blog.title}}</h4>
    <h5 class="message">{{blog.content}}</h5>
    <div class="actionBtns">
      <div class="left">
        <div class="favorite">
          <i onclick="like('{{blog.pk}}')" class="bi bi-heart-fill" id="heart_{{blog.pk}}"></i>

        </div>
        <div style=" margin-top: -1.05px;">

          <i onclick="comment('{{blog.pk}}')" class="bi bi-chat-fill chat"></i>

        </div>

        <div>
          <h4 class="likes"><span id="likes_{{blog.pk}}">{{blog.total_likes}}</span> likes</h4>
        </div>

      </div>
    </div>

    <form class="commentForm" id="commentform_{{blog.pk}}" method="get">
      <input hidden type="text" name="id_post" value = "{{blog.pk}}"  >
      <div class="addComment">
        <div class="userImg">
          <img class="cover" src="{{user.profile.image.url}}" alt="">
        </div>
        <input type="text" class="text" id = "comment_body_{{blog.pk}}" placeholder="Add a comment..." required="" name="comment" >
        <button style="border: none; margin-right: 20px;"><i class="bi bi-send"></i></button>
      </div>

    </form>


    <h4 class="comment">View all comments</h4>

    <div class="comment"  id="comment_{{blog.pk}}" style="display: none; margin-top: 15px;">
      {%for cmt in comment_post.all.reverse%}
                
      {%if cmt.post == blog%}
        <div>
            <img src="/user/media/{{cmt.name.profile.image}}" 
                        style="height: 30px; width:30px"
                        class="border border-success rounded-circle" />
         
          <span class="tag is-light is-medium">
              {{cmt.body}}
          </span>

          <span class="is-small has-text-grey-light">
            ({{ cmt.date_added }} by {{ cmt.name.username }})
        </span>
        </div>  
        </br>
      {%endif%}
      {%endfor%}
    </div>
  </div>


  {% endfor %}
</div>
<div class="follows">
  <div class="follows-table" style="overflow-y: hidden; ">
    <div style="color: black; margin-bottom: 20px;">Follow by you</div>
    {% for following in profile.following.all %}

    <hr>
    <a href="/profile/{{ following.user.profile.pk }}" style="text-decoration: none; color: #524b4b;">
      <div style="margin-left: 21px;" class="profile">
        <img class="rounded-circle account-img av" src="/user/media/{{ following.user.profile.image }}" alt="">
        <span class="follow-name">{{ following.user.username }}</span>
      </div>
    </a>
    {% endfor %}
  </div>
</div>


{% for p in post %}
<p style="display: none;" id="likepost">{{p.pk}}</p>
{% endfor %}

{% for mypost in mypost %}
<p style="display: none;" id="mypost">{{mypost.pk}}</p>
{% endfor %}
<script>
  var mypost = document.querySelectorAll("#mypost")
  for (let i = 0; i < mypost.length; i++) {
    document.getElementById("action_" + mypost[i].innerHTML).style.display = "block"
  }
  var likepost = document.querySelectorAll("#likepost")
  for (let i = 0; i < likepost.length; i++) {
    document.getElementById("heart_" + likepost[i].innerHTML).style.color = "red"
  }

  function comment(id) {
    const cmt = document.getElementById("comment_" + id)

    if (cmt.style.display == "none") {
      cmt.style.display = "block";

    }
    else {
      cmt.style.display = "none";

    }

  }




 






  function like(id) {


    const like = document.getElementById("heart_" + id)
    let countlike = document.getElementById("likes_" + id)

    if (!like.style.color) {
      like.style.color = "red";

    }
    else {
      like.style.color = ""

    }

    $.ajax({
      url: 'likes/',
      type: 'get',
      data: {
        button_like: id,

      },
      success: function (response) {
        console.log(response["valid"])
        post_like = response["post_like"]
        console.log(response["post_like"])
        countlike.innerHTML = ""
        countlike.innerHTML = post_like

      }
    })

  }



</script>

<script>
  function ConfirmDelete()
  {
    var x = confirm("Are you sure you want to delete? ");
  
    if (x)
        return true;
    else
      return false;
  }
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

{% endblock %}

onstagram/blog/templates/blog/newpost.html
{% extends "blog/base.html" %}

{% block title %}About{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
<style>
    label,h1 {
    font-weight: bold;
    margin-bottom: 10px;
    margin-top: 10px;
}
</style>
<div class="col-md-8 m-auto">
    <div class="content-section">
        <h1 class="subtitle is-2" style="color: blueviolet;">News Post</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_title">Title:</label><br>
            <input class="input is-primary" type="text" name="title"  placeholder="Title something..." maxlength="150" required id="id_title"><br>
            <label for="id_content">Content:</label><br>
            <textarea name="content" cols="30" rows="10" placeholder="Dweet something..."  class="textarea is-link" required id="id_content"></textarea>
            <input type="hidden" name="date_posted" value="2022-11-01 07:08:19" required id="id_date_posted">
            <input type="hidden" name="initial-date_posted" value="2022-11-01 07:08:19" id="initial-id_date_posted">
            <label for="id_post_image">Pictures:</label><br>
            <img class="rounded-circle account-img" src="/user/media/image/defau.jpg" alt="" id="preview-img">
            <input type="file" name="post_image" accept="image/*" id="id_post_image">
            <button class="button is-success is-fullwidth is-medium mt-5"
                    type="submit">Post News
            </button>
        </form>
        
        <br>

    </div>
</div>
<script>
    const reader = new FileReader();
    const fileInput = document.getElementById("id_post_image");
    const img = document.getElementById("preview-img");
    reader.onload = e => {
        img.src = e.target.result;
    }
    fileInput.addEventListener('change', e => {
        const f = e.target.files[0];
        reader.readAsDataURL(f);
    })
</script>
<script>
    var date = new Date();
    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();
    var hours =date.getHours();
    var miu =date.getMinutes();
    var secon =date.getSeconds();
    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
    var today = year + "-" + month + "-" + day + " " +hours+":"+miu+":"+secon;    
    document.getElementById("id_date_posted").value = today;
    </script>
{% endblock %}