onstagram/blog/urls.py
from django.urls import path
from . import views
from .views import  dashboard,newpost,mypost,delete,search,likes,editpost, comment
urlpatterns = [
    path('indexdashboard/',dashboard, name='indexdashboard'),
    path('about/', views.about, name='about'),
    path('home/', views.home, name='home'),
    path('post/',newpost, name='postnew'),
    path('mypost/',mypost, name='mypost'),
    path('delete/<str:id>/', delete, name="delete"),
    path('search/',search, name='search'),
    path('editpost/<str:id>/',editpost, name='editpost'),
    path('home/likes/', likes, name='likes'),
    path('home/comment/', comment , name='comment'),
]

onstagram/onstagram/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("user.urls")),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onstagram/user/urls.py
from django.urls import path,include
from user.views import dashboard
from user.views import login1,register,profile,follows,follower,follow

urlpatterns = [
    path("",login1,name="login1"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", dashboard, name="dashboard"),
    path("register/", register, name="register"),
    path("profile/<int:pk>",profile,name="profile"),
    path("follows/<int:pk>",follows,name="follows"),
    path("follower/",follower),
    path("follows/",follow)
    
]

onstagram/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

""" Model for User Profile """

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    following = models.ManyToManyField("self", related_name="follow_by", symmetrical=False,blank=True)
    date_of_birth = models.CharField(blank=True,max_length=150)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='image/default.png', upload_to='image',blank=True, null=True)


    def profile_posts(self):
        return self.user.post_set.all()

    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        if created:
            user_profile = Profile(user=instance)
            user_profile.save()
            # user_profile.following.add(instance.profile)
            # user_profile.save()

    # def __str__(self):
    #     return f'{self.user.username} Profile'

onstagram/user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile
from PIL import Image

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('first_name','last_name',"email",)

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

class ProfileUpdateForm(forms.ModelForm):
    # x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    # y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    # width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    # height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    # image = forms.ImageField(label=('Image'), error_messages = {'invalid':("Image files only")}, widget=forms.FileInput, required=False)
    class Meta:
        model = Profile
        fields = ['date_of_birth','image']


    # """Saving Cropped Image"""
    # def save(self,*args,**kwargs):
    #     img = super(ProfileUpdateForm, self).save(*args, **kwargs)

    #     x = self.cleaned_data.get('x')
    #     y = self.cleaned_data.get('y')
    #     w = self.cleaned_data.get('width')
    #     h = self.cleaned_data.get('height')

    #     if x and y and w and h:
    #         image = Image.open(img.image)
    #         cropped_image = image.crop((x, y, w+x, h+y))
    #         resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
    #         resized_image.save(img.image.path)

    #     return img

onstagram/user/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from user.forms import CustomUserCreationForm,UserUpdateForm,ProfileUpdateForm
from django.contrib.auth import login
from django.contrib import messages
from .models import Profile
from blog.models import Post
from django.contrib.auth.decorators import login_required

@login_required
def dashboard(request):
    return render(request, "users/dashboard.html")

@login_required
def login1(request):
    response = redirect('accounts/login/')
    return response

def register(request):
    if request.method == "GET":
        return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("http://localhost:8000/accounts/login/")
        else:
            return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm})

@login_required
def profile(request, pk):
    if(request.method == 'GET'):
        profile = Profile.objects.get(pk=pk)
        profile.following.add(profile)

        iduser = str(request.user.profile.pk)
        idlink = str(pk)

        post = Post.objects.filter(
        author=request.user
        )
       
        return render(request, "users/profile.html",{"profile": profile,'iduser': iduser,'idlink': idlink,'blogs':post})

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
       
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Your account has been updated!")
            return redirect('/profile/'+str(pk))
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

@login_required  
def follows (request,pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("following")
        if action == "follow":
            current_user_profile.following.add(profile)
        elif action == "unfollow":
            current_user_profile.following.remove(profile)
        current_user_profile.save()   
    return redirect('/profile/'+str(pk))
@login_required
def follower(request):
     profile = Profile.objects.get(pk=request.user.profile.pk) 
     return render(
        request ,
        "users/follower.html",{"profile":profile})
@login_required
def follow(request):
     profile = Profile.objects.get(pk=request.user.profile.pk)
     return render(
        request ,
        "users/follows.html",{"profile":profile})

onstagram/user/templates/users/dashboard.html
{% extends 'base.html' %}

{% block content %}
Hello, {{ user.username|default:'Guest' }}!

<div>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>
{% endblock %}

onstagram/user/templates/users/follower.html
{% extends "blog/base.html" %}

{% block title %}Follower{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
<div class="col-md-8 m-auto">
    <div class="content-section">
        <h1 class="subtitle is-2">Follower</h1>
        <div class="follow-follower">
            <div class="block">
                <div class="content">
                    <ul class="menu-list" style="list-style-type: none;">
                        {% for follower in profile.follow_by.all %}
                        <a href="/profile/{{ follower.user.profile.pk }}" style="text-decoration: none; color: #524b4b;">
                            <li class="box"  style="margin-bottom: 20px;">
                                <img class="rounded-circle account-img" src="/user/media/{{ follower.user.profile.image }}" alt=""
                                    id="preview-img">

                                    <span style="font-size: 25px;font-weight: 600;"> {{ follower.user.username }}</span>

                            </li>
                        </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

onstagram/user/templates/users/follows.html
{% extends "blog/base.html" %}

{% block title %}Follows{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
<div class="col-md-8 m-auto">
    <div class="content-section">
        <h1 class="subtitle is-2">Follow by you</h1>
        <div class="block">
            <div class="content">
                <ul class="menu-list"  style="list-style-type: none;">
                    {% for following in profile.following.all %}
                    <a href="/profile/{{ following.user.profile.pk }}" style="text-decoration: none; color: #524b4b;">
                        <li class="box" style="margin-bottom: 20px; list-style-type: none;">
                            <img class="rounded-circle account-img" src="/user/media/{{ following.user.profile.image }}" alt=""
                                id="preview-img">

                           <span style="font-size: 25px;font-weight: 600;">{{ following.user.username }}</span> 

                        </li>
                    </a>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <br>

    </div>
</div>


{% endblock %}

onstagram/user/templates/users/profile.html
{% extends 'blog/base.html' %}
{% block title %}Profile{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
<link rel="stylesheet" href="{% static 'css/profile.css'%}">

<style>
    h2 {
        font-weight: bold;
        margin-bottom: 10px;
        margin-top: 10px;
    }
</style>
<div class="main" style="display: flex; width: 100%;">
    <div class="column">

        <div class="block" style="display: flex;align-items: center;">
            <img class="rounded-circle account-img" src="/user/media/{{ profile.image }}" alt="">

            <h1 class="title is-1" style="margin-bottom: 0px;">
                {{profile.user.username}}
            </h1>
            <p onclick="edit1()" id="edit_user" class="button is-danger is-active"
                style="margin-left: 30px;text-decoration: none;font-size: 13px; background-color: #FF5858;border-radius: 10px;">
                <ion-icon name="settings-outline" style="margin-right: 5px;"></ion-icon>Edit profile
            </p>

        </div>
        <form method="post" action="/follows/{{profile.pk}}">
            {% csrf_token %}
            <div class="buttons has-addons" id="container-btn">
                {% if profile in user.profile.following.all %}
                <button class="button is-success is-static">Follow</button>
                <button class="button is-danger" name="following" value="unfollow">
                    Unfollow
                </button>
                {% else %}
                <button class="button is-success" name="following" value="follow">
                    Follow
                </button>
                <button class="button is-danger is-static">Unfollow</button>
                {% endif %}
            </div>
        </form>
        <input type="hidden" value=" {{iduser}}" id="iduser">
        <input type="hidden" value=" {{idlink}}" id="idlink">
        <div class="modal" id="editprofile">
            <div class="modal-background"></div>
            <div class="modal-card">
                <header class="modal-card-head">

                    <p class="modal-card-title" style=""> {{profile.user.username}}</p>
                    <button class="delete" aria-label="close" onclick="closemodal()"></button>
                </header>

                <form id="editprofileform" action="" method="post" enctype="multipart/form-data"
                    style="overflow-y: scroll;">
                    {% csrf_token %}
                    <section class="modal-card-body">
                        <h2>First Name</h2>
                        <input class="input is-primary" type="text" name="first_name" maxlength="150" id="id_first_name"
                            placeholder="First Name" value="{{ profile.user.first_name }}">
                        <h2>Last Name</h2>
                        <input class="input is-link" type="text" name="last_name" maxlength="150" id="id_last_name"
                            placeholder="Last Name" value="{{ profile.user.last_name }}">
                        <h2>Email</h2>
                        <input class="input is-info" type="email" name="email" maxlength="254" id="id_email"
                            placeholder="Email" value="{{ profile.user.email }}">
                        <h2>Date Of Birth</h2>
                        <input class="input is-danger" type="date" name="date_of_birth"
                            value="{{ profile.date_of_birth }}">
                        <h2>Avatar</h2>
                        <img class="rounded-circle account-img" src="/user/media/{{ profile.image }}" alt=""
                            id="preview-img">
                        <input type="file" name="image" id="file">
                        <label for="file" class="btn-3">
                            <span id="upload">
                                <ion-icon name="cloud-upload-outline" style="margin-right: 5px;"></ion-icon> Select
                                picture
                            </span>
                        </label>
                    </section>
                    <footer class="modal-card-foot">
                        <button type="button" class="button is-success" onclick="checkform()">Save changes</button>
                        <span class="button" onclick="closemodal()"> Cancel</span>
                    </footer>
                </form>
            </div>
        </div>
        <div class="container" style="display: flex;">
            <div style="flex: 2;">
            </div>
        </div>
    </div>
</div>
<div class="post" id="post">
    {% for blog in blogs %}
    <div class="card">
        <div class="top">
            <div class="userDetails">
                <div class="profile_img">
                    <img class="cover" src="/user/media/{{blog.author.profile.image}}" alt="">
                </div>
                <div>
                    <h3>{{blog.author.username}}</h3>
                    <span class="postTime">{{ blog.date_posted }}</span>
                </div>
            </div>
            <div>
                <a href="{% url 'editpost' blog.id %}"><i style="color: black;" class="fa fa-cog"
                        aria-hidden="true"></i></a>
                <a style="margin-left: 10px;" href="{% url 'delete' blog.id %}" Onclick="return ConfirmDelete();"><i
                        style="color: black;" class="fa fa-trash" aria-hidden="true"></i>

                </a>
            </div>
        </div>
        <div class="imgBx">
            <img class="cover" src="/user/media/{{blog.post_image}}" alt="">
        </div>
        <div class="actionBtns">
            <div class="left">
                <div>
                    <i onclick="like('{{blog.pk}}')" class="bi bi-heart-fill" id="heart_{{blog.pk}}"></i>
                </div>
                <div style=" margin-top: -1.05px;">
                    <i class="bi bi-chat-fill chat"></i>
                </div>

            </div>
        </div>
        <h4 class="likes"><span id="likes_{{blog.pk}}">{{blog.total_likes}}</span> likes</h4>
        <h4 class="title">{{blog.title}}</h4>
        <h5 class="message">{{blog.content}}</h5>
        <h4 class="comment">View all 20 comments</h4>
        <div class="addComment">
            <div class="userImg">
                <img class="cover" src="/user/media/{{blog.post_image}}" alt="">
            </div>
            <input type="text" class="text" placeholder="Add a comment...">
        </div>

    </div>
    {% endfor %}
</div>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script>

    var iduser = document.getElementById("iduser").value
    var idlink = document.getElementById("idlink").value
    var container_btn = document.getElementById("container-btn")
    if (iduser == idlink) {
        container_btn.style.display = "none"
    }
    if (iduser != idlink) {
        document.getElementById("edit_user").style.display = "none"
        document.getElementById("post").style.display = "none"
    }

    function checkform() {
        var first_name = document.getElementById("id_first_name").value
        var last_name = document.getElementById("id_last_name").value
        var email = document.getElementById("id_email").value

        if (!first_name || !last_name || !email)
            alert("First name, last name, email cannot be left blank")
        else
            document.getElementById("editprofileform").submit()
    }

    function edit1() {
        var editprofile = document.getElementById("editprofile")
        editprofile.style.display = "flex"
        editprofile.style.justifyContent = "center"
        editprofile.style.alignItems = "center"

    }

    function closemodal() {
        var editprofile = document.getElementById("editprofile")
        editprofile.style.display = "none"
    }
</script>
<script>
    const reader = new FileReader();
    const fileInput = document.getElementById("file");
    const img = document.getElementById("preview-img");
    reader.onload = e => {
        img.src = e.target.result;
    }
    fileInput.addEventListener('change', e => {
        const f = e.target.files[0];
        reader.readAsDataURL(f);
    })
</script>
<script>
    function ConfirmDelete()
    {
      var x = confirm("Are you sure you want to delete? ");
    
      if (x)
          return true;
      else
        return false;
    }
  </script>
{% endblock content %}

onstagram/user/templates/users/register.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/register1.css' %}">
<main>
    <div class="page">
        <div class="header">

            <h1 class="logo">𝓞𝓷𝓼𝓽𝓪𝓰𝓻𝓪𝓶</h1>
           
  
        </div>
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username"
                    autofocus="" required="" id="id_username" placeholder="Username">
                <input type="text" name="first_name" maxlength="150" id="id_first_name" placeholder="First Name">
                <input type="text" name="last_name" maxlength="150" id="id_last_name" placeholder="Last Name">
                <input type="email" name="email" maxlength="254" id="id_email" placeholder="Email">
                <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" placeholder="Password">
                <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="Comfirm Password">
                <button type="submit">Sign up</button>
            </form>

            <ul>
                <li>By signing up, you agree to our</li>
                <li><a href="">Terms</a></li>
                <li><a href="">Data Policy</a></li>
                <li>and</li>
                <li><a href="">Cookies Policy</a> .</li>
            </ul>
        </div>
    </div>
    </div>
    <div class="option">
        <p>Have an account? <a href="{% url 'login' %}">Log in</a></p>
    </div>

    
</main>